### ISSUE TITLE
movies are not adding to watchlist

### ISSUE THREAD

**Issue by dennysunny** [RichardVerbraak/Vizier#1]
when click on add to watchlist..it is not adding to thw watchlist..

**Comment by RichardVerbraak** [comment]
Hi Denny,

This is because I haven't set up my Redux state to pull the saved movies from Firebase and display these on the WatchListPage (yet). Currently they are only stored on Firebase when you click the button, I'll also need to add authentication so the movies can be tracked per user.

**Comment by dennysunny** [comment]
Okay thank you, I'm currently learning these all and using your code as reference
